name: server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: server

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -o placebot-web-linux-amd64
    
    - uses: actions/upload-artifact@v3
      with:
        name: placebot-server.zip
        path: server/placebot-web-linux-amd64
